include/oneapi/dpl/experimental/kt/esimd_radix_sort_one_wg.h - fix compile error for int16_t type: ../include/sycl/ext/intel/experimental/esimd/memory.hpp:381:3: error: static assertion failed due to requirement '_DS == lsc_data_size::u32 || _DS == lsc_data_size::u64': Transposed load is supported only for data size u32 or u64
(cherry picked from commit b88d999a75668ee32b402e1310f936d83f5d0545)