[KT] Implement & test esimd radix sort for int16_t and uint16_t (#966)
Also we made change in one_wg_kernel function:
- we replace block of code
            #pragma unroll
            for (uint32_t s = 0; s<PROCESS_SIZE; s+=64){
                keys.template select<64, 1>(s) = lsc_slm_block_load<KeyT, 64>(slm_reorder_this_thread+s*sizeof(KeyT));
            }
to
            keys = utils::BlockLoad<KeyT, PROCESS_SIZE>(slm_reorder_this_thread);
to avoid compile error:
../include/sycl/ext/intel/experimental/esimd/memory.hpp:381:3: error: static assertion failed due to requirement '_DS == lsc_data_size::u32 || _DS == lsc_data_size::u64': Transposed load is supported only for data size u32 or u64