Revert "Finclude/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h - fix compile error in transform_init : src/include/oneapi/dpl/pstl/tuple_impl.h:285:21: error: cannot assign to non-static data member 'value' with const-qualified type 'const int &'"
This reverts commit 9260fe424d47edc4be42794440b2f30a1e8712aa.