test/support/test_config.h - fix compile error: no member named 'binary_negate' in namespace 'std'
    include\oneapi/dpl/internal/../functional(51,14): error: no member named 'binary_negate' in namespace 'std'
    using ::std::binary_negate; // Deprecated in C++17, removed in C++20